---
- hosts: "{{host_group}}"
  become: true
  become_method: sudo

  vars_files:
  - vars/remote_mach_vars.yml

  tasks:
  # Update apt-get
  - name: update apt-get
    apt: upgrade=dist update_cache=yes

  # Install packages
  - name: install packages
    apt: pkg={{ item }} state=present
    with_items:
      - git
      - python-pexpect
      - apache2
      - nodejs
      - npm
      - build-essential
      - daemon

...
